"""empty message

Revision ID: 99d2c1d0e92d
Revises: 9d1f4443f9bc
Create Date: 2021-03-22 21:15:21.025099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d2c1d0e92d'
down_revision = '9d1f4443f9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('role', 'description')
    # ### end Alembic commands ###
